name: Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build ReScript
        run: yarn rescript build

      - name: Execute Tests
        run: yarn test run
